export { default as Clothing } from "./Clothing";
export { default as Gents } from "./Gents";
export { default as Kids } from "./Kids";
export { default as Ladies } from "./Ladies";
export { default as Admin } from "./Admin";
export { default as Pets } from "./Pets";
export { default as Kitchen } from "./Kitchen";
export { default as Home } from "./Home";
export { default as Updateform } from "./Updateform";
